// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcfjmxohmccyyhnttzvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjZmpteG9obWNjeXlobnR0enZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI2NDYwOTIsImV4cCI6MjA0ODIyMjA5Mn0.CRS4snWpRBvx-Jz4rxCUj9n0yhTSMjZm6_paZL8CqsE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);